### PR TITLE
Setting the status to FAILED for UNSTABLE builds

### PR DESCRIPTION
**Pull request by nbali**

### CODE REVIEW

**Comment by nbali** [comment]
@amansilla test failures could appear "only" as unstable, but they are marked usually/should be marked as failed in cases like this

**Comment by amansilla** [comment]
@nbali  First thank you for your contribution. Following the recommendations of jenkins-ci in the document above, could you please create a ticket in the issue tracker to describe the the feature you are implementing. This creates the permanent record on our system that later allows future developers to understand how the code came into the current shape. This is not a requirement, but we appreciate if you do that.

**Comment by pdjtrifork** [comment]
Nice...looking forward to getting this fix added to our jenkins :)

**Comment by amansilla** [comment]
@nbali Thanks you :smile:

**Comment by nbali** [comment]
@amansilla sorry for not doing it the "proper" way, but solving this issue on our jenkins was already a side-job of a side-job for me

**Pull request merged**
