### PR TITLE
Remove the dependency on Multiple SCMs plugin

### PR DESCRIPTION
**Pull request by mrrsm**
Fixes JENKINS-62882 
Remove the dependency on the Multiple SCMs plugin as it has been deprecated and appears to have many functional issues

### CODE REVIEW

**Review by HeidiRechek — APPROVED** [review]

**Review by HeidiRechek — APPROVED** [review]

**Comment by Joeb454** [comment]
There was another PR for this, but this one looks like it's probably the better solution. Does anybody know how we can get this merged and updated, or if the plugin is even being maintained anymore? This issue has been outstanding for over 1 year already.

**Comment by mrrsm** [comment]
@amansilla You are the person who merged the last PR's here.  Are you still the maintainer of this project?

**Review by nibty — APPROVED** [review]
Looks good

**Comment by Hildebrand-Ritense** [comment]
@amansilla would you be so kind to please review this PR? It would really help keep Jenkins up to date with not deprecated plugin dependencies. Thank you.

**Comment by amansilla** [comment]
Sorry for the time awaiting for this PR to be merged. @mrrsm thx for your contribution.

**Review by amansilla — APPROVED** [review]

**Comment by yateya** [comment]
Thanks for the fix. Will the new release appear in jenkins plugin manager soon?

**Comment by MeyerOppelt** [comment]
@amansilla 
Since this issue has been fixed, would you please release a new build on the archive repository. The [latest build](https://ci.jenkins.io/job/Plugins/job/bitbucket-build-status-notifier-plugin/job/master/) is free of this issue, and still works. Nobody else can release a new build since you’re the project maintainer. 
While we can manually install the hpi, I think it dissuades new users from your plugin because of its issues with the download from the archive repo.
Thank you :)

**Pull request merged**
