### PR TITLE
added ability to select a single repo to notify from the Multiple SCM…

### PR DESCRIPTION
**Pull request by cschwarz-inco**
As per your comments I forked the repo and added the required functionality. I tested it with my Jenkins and it works fine. Please consider for merge. Thank you, Chris.

### CODE REVIEW

**Comment by amansilla** [comment]
@cschwarz-inco thanks for your contribution. I'll check this and give you feedback asap.

**Comment by amansilla** [comment]
Hi @cschwarz-inco, first thank you for your contribution.

I've checked today your changes but I've found the following problems, which should be fixed before this to be merged.

- What if I want to notify all the reposories if I'm using multiple repositories? That's not possible anymore.
- Your current implementation would allow to insert a URL in the Bitbucket notifier configuration, which is still even not being used in the MultiSCM configuration, which is wrong.

I think the solution would be to show all SCM URLs (directly from the Multi SCM configuration and not editable) with a check box for each, which would mean if that repo is going to be notified or not. It should also be necessary to check that there is at least one is selected. 

Do you think you could fix this? Otherwise I'll close the pull request, since the proposed solution is more some kind of workaround than a the real solution to this problem.

**Comment by cschwarz-inco** [comment]
* if you don't set a Multi SCM Repo URL, it will notify all repositories, just like it did before
* yes you can configure an URL that does not correspond with any of the configured SCMs. In this case there won't be a notification as the code is unable to identify an existing SCM. This is a configuration error and can easily be detected and fixed by the user. Showing all configured URLs would not help, what if an SCM that is configured for notification is removed later in the Multi SCM module? Than you end up in the same situation. Also, I would have to do more research as how to add dynamic content to the configuration screens. At the moment everything is static.
* BTW I doubt that notifying multiple repos would work anyway. That's because it seems to get only one SHA-1 commit ID (via buildData.getLastBuiltRevision() which is not related to any particular repo). But each git repo is at a different commmit ID so that one ID can not work for all of them. It seems to work now for me but that might be coincidence because the repo I want to notify is the first in list.
I agree this needs more testing and work but I won't have much time for it in the near future.

**Comment by amansilla** [comment]
I got your problems, but all them can be solved in a better way I guess. Since you've no time to fix this, I'm going to close the pull request and start working in order the plugin supports choosing which SCM URLs should be notified.

Anyways thank you very much for your contribution to this plugin. ;).

**Pull request closed without merging**
