### PR TITLE
Use MercurialTagAction.class to retrive Mercurial revision

### PR DESCRIPTION
**Pull request by bguerin**
hgSCM.getRevision() is sometimes broken, do not know why ...

### CODE REVIEW

**Comment by amansilla** [comment]
Hi @bguerin, first thank you for this PR. Could you please say me whether you are using the plugin in a "free style project" or a "pipeline"? Both solutions should work after this patch is applied.

**Comment by bguerin** [comment]
Free style and maven projects, no pipeline. But I can test my patch on pipeline projects :)

**Comment by amansilla** [comment]
Thx for the feedback @bguerin I'd apreciate so much if you can complete test it, inclusive the pipeline.

**Comment by bguerin** [comment]
tested ok on a pipeline job :)

**Comment by amansilla** [comment]
Thx @bguerin for your colaboration, your fix will be included on the next plugin release.

**Pull request merged**
