### PR TITLE
[JENKINS-32633] Add support for multi repositories

### PR DESCRIPTION
**Pull request by amansilla**
This add support for MultiSCM since #7 was not updated to work with the plugin current code. I hope it works as desired and wait for users feedback to be merged.

### CODE REVIEW

**Comment by stevejensen22** [comment]
Thanks so much for the work you do. I have used this plugin for a while with a single git repository and it works great!

Does multi-scm notifications actually work? I have build status notifications working for a jenkins job with a single Git repository. But when I attempt to use `Multiple SCMs` even if there are multiple changes on multiple repositories since the last test run (*that bitbucket should be notified of*), I only get **one** message: `Sending build status INPROGRESS for commit 123426541658168asdf to BitBucket is done!` and when I go look at that commit, the status indicator is not displayed. Is there some configuration option I am missing to make mult-scm work?

> It should have a configuration option that selects the repo or repos to notify.

I am fine with it blasting notification to all the repositories I have specified in my jenkins config, I just want this to work.

**Summary: I can't get any build status notifications at all if I have multiple scm's configured**

Thanks again!

**Comment by yakobe** [comment]
@stevejensen22 just out of interest, how long are your branch names / jenkins job names? I had a problem where the status was not updated on bitbucket if they were too long. When i tried on on a short name (i.e. master) it worked.

**Comment by stevejensen22** [comment]
@yakobe thanks so much for the interest.  I appreciate it.  Though, I am not sure if that is the problem as build status notifications are working fine on the same jenkins job / branch name if I use a single `Git` repository rather than multiple `Git` repositories using the `Multiple SCMs` option.

But to answer your question the branch name is `mbo_chrome_high` and the branch is `master`

**Comment by stevejensen22** [comment]
`UPDATE`: I just added some logging to the plugin to gain some insight on my issue. It appears that only pipelines are supported. I have added support for FreeStyleProjects but I am getting the same commit ID for every repo. But at least one of those ID's is for the right repo and I'm get notifications! Still digging...

**Comment by stevejensen22** [comment]
I think I figured out the single commit id issue. I am using multi-scm in order to attempt to send build status notifcations to different repositories which shows multiple last build revisions as shown 👇 

screen shot 2016-08-11 at 3 59 00 pm

This status notifier plugin uses buildData.getLastBuiltRevision() which only grabs the first commit id from the list above. Any idea as to how I could do this differently?

Something like buildData.getLastBuildRevisions() which returned a list of revisions would do the trick. I'll look into the Git plugin.

**Comment by amansilla** [comment]
Hi @stevejensen22 I guess the multi scm support was broken within the last plugin release. Which plugin version are you using? If is the 1.3.0 and you don't need the pipeline functionality, please try to downgrade the plugin to 1.2.2.

**Comment by stevejensen22** [comment]
@amansilla so you have had this working the way I've explained ☝️ ? With multiple revisions all being notified to the correct repositories? So for the picture above the console should look something like this...

```
Sending build status SUCCESSFUL for commit blablablablablablablablabla to BitBucket is done!
Sending build status SUCCESSFUL for commit dadadadadadadadadadada to BitBucket is done!
Sending build status SUCCESSFUL for commit yayayayayayayayayayayaya to BitBucket is done!
Sending build status SUCCESSFUL for commit rararararararararararararara to BitBucket is done!
```

And each of those notifications would be targeting the appropriate repositories?

**Comment by amansilla** [comment]
Hi again @stevejensen22 as soon as I now the 1.2.2 version should work as you describe. At the moment I've not much time to check why that's not working but I'll do it asap.

**Pull request merged**
