### PR TITLE
[JENKINS-32548] Added support for mercurial repositories

### PR DESCRIPTION
**Pull request by dbuedo**
Added support for mercurial repositories.

### CODE REVIEW

**Comment by amansilla** [comment]
Hi @dbuedo, did you already find the way to get the current revision for mercurial repositories as in #2 was spoken?

**Comment by dbuedo** [comment]
@amansilla Yes, by calling MercurialSCM.getRevision(). 
At least for the scenaries I have tried it does the job:

1. Build an existing job with one new change in the repository
2. Build an existing job with more than one new changes in the repository
3. Build an existing job with no new changes in the repository
4. Create and build a new job with new changes (not notified yet) in the repository
5. Create and build a new job with no new changes in the repository

For scenaries 4 and 5 log shows a confusing WARN message because there isn't a previous change log, but I get CommitId successfully and Bitbucket is notified correctly: 
```
WARN: Revision data for previous build unavailable; unable to determine change log
Sending build status INPROGRESS for commit default to BitBucket is done!
Sending build status SUCCESSFUL for commit default to BitBucket is done!
Finished: SUCCESS
```

**Comment by amansilla** [comment]
Good job @dbuedo, thank you very much for so good explained test cases at some point we should add this tests to the test suit since it's a bit annoying to test this manually :smile:. I'll check and merge this asap.

**Comment by amansilla** [comment]
@dbuedo thanks again for your contribution, the support for mercurial repositories was merged and will be released soon, probably next monday.

**Pull request merged**
