### PR TITLE
[JENKINS-32633] Support for MultiSCM.

### PR DESCRIPTION
**Pull request by MarekFort**
This patch adds support for MultiSCM. The same build status is sent to all Git repos.

### CODE REVIEW

**Comment by amansilla** [comment]
@MarekFort First thank you for your contribution. Following the recommendations of jenkins-ci in the document above, could you please create a ticket in the issue tracker to describe the the feature you are implementing. This creates the permanent record on our system that later allows future developers to understand how the code came into the current shape. We'll appreciate if you do that.

**Comment by zerthimon** [comment]
@MarekFort 
```
The same build status is sent to all Git repos.
```

I have a number of git repos I checkout for the build, some of them are not even in bitbucket. So I would not want to send status for all the repos. Perhaps make this a configuration option, or send the status to the last repo in list.

**Comment by attrib** [comment]
+1 for this!

What is needed for this to get merged?

**Comment by amansilla** [comment]
Hey @MarekFort can you please rebase this with the current master and update this? I would like to include your functionality but it still needs to be updated with the last changes added to the current plugin version.

Thanks again

**Comment by adrai** [comment]
+1 for this too!

**Comment by amansilla** [comment]
This will be closed since contributor doesn't answer and #14 add this feature implemented for the current plugin version.

**Pull request closed without merging**
